name: Publish Image

on:
  workflow_call:
    inputs:
      app:
        description: 'The application to build'
        type: string
        required: true
      tag:
        description: 'The tag to use for the image'
        type: string
        required: true
      file:
        description: 'The Dockerfile to use for the build'
        type: string
        required: false
        default: 'Dockerfile'
      context:
        description: 'The context to use for the build'
        type: string
        required: false
        default: '.'

jobs:
  publish-image:
    runs-on: self-hosted
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          registry: registry.jnhssg.de
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: registry.jnhssg.de/${{inputs.app}}:${{ inputs.tag }}
          platforms: linux/arm64
          file: ${{ inputs.file }}
          context: ${{ inputs.context }}
          build-args: |
            VERSION=${{ inputs.tag }}
